"""Tests for git API endpoints (Story 39.25)."""

import pytest
from pathlib import Path
from fastapi.testclient import TestClient
from gao_dev.web.server import create_app
from gao_dev.web.config import WebConfig
from gao_dev.core.git_manager import GitManager


@pytest.fixture
def git_test_project(tmp_path):
    """Create a test project with git repository and commits."""
    project_dir = tmp_path / "test_project"
    project_dir.mkdir()

    # Initialize git repository
    git_manager = GitManager(project_path=project_dir)
    git_manager.init_repo(
        user_name="Test User",
        user_email="test@example.com",
        initial_commit=True,
        create_gitignore=True,
    )

    # Create some test files and commits
    test_file_1 = project_dir / "file1.txt"
    test_file_1.write_text("Line 1\nLine 2\nLine 3\n")
    git_manager.add_all()
    git_manager.commit("feat(test): add file1.txt\n\nFirst feature commit")

    test_file_2 = project_dir / "file2.txt"
    test_file_2.write_text("Content of file 2\n")
    git_manager.add_all()
    git_manager.commit("fix(test): add file2.txt\n\nBug fix commit")

    # Modify file1 to create more changes
    test_file_1.write_text("Line 1\nLine 2\nLine 3\nLine 4\nLine 5\n")
    git_manager.add_all()
    git_manager.commit("refactor(test): update file1.txt\n\nRefactor commit")

    # Agent commit (different email)
    test_file_3 = project_dir / "agent_file.txt"
    test_file_3.write_text("Agent generated file\n")
    git_manager._run_git_command(["config", "user.email", "agent@gao-dev.local"])
    git_manager.add_all()
    git_manager.commit("feat(agent): add agent file\n\nGenerated by agent")

    # Reset email
    git_manager._run_git_command(["config", "user.email", "test@example.com"])

    return project_dir


@pytest.fixture
def test_client(git_test_project):
    """Create test client with git project."""
    # Create .gao-dev directory
    (git_test_project / ".gao-dev").mkdir(exist_ok=True)

    # Create config with frontend dist path
    frontend_dist = git_test_project / "frontend" / "dist"
    frontend_dist.mkdir(parents=True, exist_ok=True)

    config = WebConfig(
        host="127.0.0.1",
        port=3000,
        auto_open=False,
        frontend_dist_path=str(frontend_dist),
    )

    app = create_app(config)
    app.state.project_root = git_test_project

    return TestClient(app)


class TestGitCommitsEndpoint:
    """Tests for /api/git/commits endpoint."""

    def test_get_commits_success(self, test_client):
        """Test successful retrieval of commit list."""
        response = test_client.get("/api/git/commits")

        assert response.status_code == 200
        data = response.json()

        # Verify response structure
        assert "commits" in data
        assert "total" in data
        assert "has_more" in data

        # Verify we have commits (initial + 3 test commits = 4 total)
        assert len(data["commits"]) >= 4
        assert data["total"] >= 4

        # Verify commit structure
        first_commit = data["commits"][0]
        assert "hash" in first_commit
        assert "short_hash" in first_commit
        assert "message" in first_commit
        assert "author" in first_commit
        assert "timestamp" in first_commit
        assert "files_changed" in first_commit
        assert "insertions" in first_commit
        assert "deletions" in first_commit

        # Verify author structure
        author = first_commit["author"]
        assert "name" in author
        assert "email" in author
        assert "is_agent" in author

    def test_get_commits_pagination(self, test_client):
        """Test pagination with limit and offset."""
        # Get first 2 commits
        response1 = test_client.get("/api/git/commits?limit=2&offset=0")
        assert response1.status_code == 200
        data1 = response1.json()
        assert len(data1["commits"]) <= 2

        # Get next 2 commits
        response2 = test_client.get("/api/git/commits?limit=2&offset=2")
        assert response2.status_code == 200
        data2 = response2.json()

        # Verify different commits
        if len(data1["commits"]) > 0 and len(data2["commits"]) > 0:
            assert data1["commits"][0]["hash"] != data2["commits"][0]["hash"]

    def test_get_commits_author_filter(self, test_client):
        """Test filtering by author."""
        # Filter by user commits
        response = test_client.get("/api/git/commits?author=test@example.com")
        assert response.status_code == 200
        data = response.json()

        # All commits should be from test user
        for commit in data["commits"]:
            assert commit["author"]["email"] == "test@example.com"
            assert commit["author"]["is_agent"] is False

    def test_get_commits_agent_detection(self, test_client):
        """Test agent commit detection."""
        # Get all commits
        response = test_client.get("/api/git/commits?limit=50")
        assert response.status_code == 200
        data = response.json()

        # Find agent commit
        agent_commits = [c for c in data["commits"] if c["author"]["is_agent"]]
        assert len(agent_commits) >= 1

        # Verify agent commit has correct email
        agent_commit = agent_commits[0]
        assert "@gao-dev.local" in agent_commit["author"]["email"]

    def test_get_commits_reverse_chronological(self, test_client):
        """Test commits are returned in reverse chronological order (newest first)."""
        response = test_client.get("/api/git/commits?limit=50")
        assert response.status_code == 200
        data = response.json()

        # Verify order (newest first)
        if len(data["commits"]) >= 2:
            from datetime import datetime

            first_time = datetime.fromisoformat(
                data["commits"][0]["timestamp"].replace("Z", "+00:00")
            )
            second_time = datetime.fromisoformat(
                data["commits"][1]["timestamp"].replace("Z", "+00:00")
            )
            assert first_time >= second_time

    def test_get_commits_empty_repo(self, tmp_path):
        """Test endpoint with empty repository (no commits)."""
        # Create empty git repo
        empty_project = tmp_path / "empty_project"
        empty_project.mkdir()
        (empty_project / ".gao-dev").mkdir()

        git_manager = GitManager(project_path=empty_project)
        git_manager.git_init()

        # Create test client
        frontend_dist = empty_project / "frontend" / "dist"
        frontend_dist.mkdir(parents=True, exist_ok=True)

        config = WebConfig(
            host="127.0.0.1",
            port=3000,
            auto_open=False,
            frontend_dist_path=str(frontend_dist),
        )

        app = create_app(config)
        app.state.project_root = empty_project

        client = TestClient(app)

        # Request commits
        response = client.get("/api/git/commits")
        assert response.status_code == 200
        data = response.json()

        # Should return empty list
        assert len(data["commits"]) == 0
        assert data["total"] == 0
        assert data["has_more"] is False

    def test_get_commits_not_git_repo(self, tmp_path):
        """Test endpoint with non-git directory."""
        # Create non-git directory
        non_git_project = tmp_path / "non_git_project"
        non_git_project.mkdir()
        (non_git_project / ".gao-dev").mkdir()

        # Create test client
        frontend_dist = non_git_project / "frontend" / "dist"
        frontend_dist.mkdir(parents=True, exist_ok=True)

        config = WebConfig(
            host="127.0.0.1",
            port=3000,
            auto_open=False,
            frontend_dist_path=str(frontend_dist),
        )

        app = create_app(config)
        app.state.project_root = non_git_project

        client = TestClient(app)

        # Request commits - should fail
        response = client.get("/api/git/commits")
        assert response.status_code == 404
        assert "Not a git repository" in response.json()["detail"]

    def test_get_commits_limit_bounds(self, test_client):
        """Test limit parameter bounds (1-100)."""
        # Valid limit
        response = test_client.get("/api/git/commits?limit=10")
        assert response.status_code == 200

        # Limit too low (should use minimum)
        response = test_client.get("/api/git/commits?limit=0")
        assert response.status_code == 422  # Validation error

        # Limit too high (should use maximum)
        response = test_client.get("/api/git/commits?limit=101")
        assert response.status_code == 422  # Validation error

    def test_get_commits_file_statistics(self, test_client):
        """Test file statistics are included in commits."""
        response = test_client.get("/api/git/commits?limit=50")
        assert response.status_code == 200
        data = response.json()

        # Find a commit with file changes
        commits_with_changes = [c for c in data["commits"] if c["files_changed"] > 0]

        assert len(commits_with_changes) > 0

        # Verify statistics
        commit = commits_with_changes[0]
        assert commit["files_changed"] >= 1
        assert commit["insertions"] >= 0
        assert commit["deletions"] >= 0
